source("common.R")
## perhaps, replace 'pamefile' by 'aoifile'
reg <- ursa:::spatialize(pamefile,resetGrid=TRUE,crs=gridCRS)
spatial_grid(reg)
reg <- spatial_buffer(reg,gridCellsize/2)
spatial_grid(reg)
session_grid(regrid(res=gridCellsize))
session_grid()
a <- ursa:::.fasterize(spatial_union(reg))
a
# display(a)
b <- polygonize(a)
spatial_data(b) <- data.frame(cell=1000000L+seq(spatial_count(b)))
series(spatial_data(b))
# glance(b)
spatial_write(b,gridfile,compress=TRUE)
